name: MLDD_Project
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pip:
      - cattrs==23.2.3
      - chembl-webresource-client==0.10.9
      - contourpy==1.2.1
      - cycler==0.12.1
      - easydict==1.13
      - et-xmlfile==1.1.0
      - filelock==3.14.0
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - joblib==1.4.2
      - kaleido==0.2.1
      - kiwisolver==1.4.5
      - matplotlib==3.8.4
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - openpyxl==3.1.2
      - pandas==2.2.2
      - pillow==10.3.0
      - plotly==5.22.0
      - pyparsing==3.1.2
      - rdkit==2023.9.6
      - requests-cache==1.2.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - sympy==1.12
      - tenacity==8.3.0
      - threadpoolctl==3.5.0
      - torch==2.3.0
      - tzdata==2024.1
      - url-normalize==1.4.3
